"""empty message

Revision ID: 2ad3b67d5269
Revises: 53309041958e
Create Date: 2023-04-12 21:35:47.029582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad3b67d5269'
down_revision = '53309041958e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('modified_at')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('modified_at')

    # ### end Alembic commands ###
