"""empty message

Revision ID: 53309041958e
Revises: 
Create Date: 2023-04-11 20:42:08.737600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53309041958e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_question_timestamp')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_question_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
